#!/bin/sh
#
# Minimal backlight manager shell script
#
# https://github.com/cherrynoize/set-light
# Author: cherrynoize
#

backlight_dir="/sys/class/backlight"
brightness_file="brightness"
max_brightness_file="max_brightness"

cur_brightness="$(cat ${backlight_dir}/*/${brightness_file})"
max_brightness="$(cat ${backlight_dir}/*/${max_brightness_file})"

min=3
max="$max_brightness"
step=5

[ -n "$2" ] && step=$2

# Give video members permission to edit brightness settings
set_rules () {
  # Backlight
  chgrp video /sys/class/backlight/*/brightness
  chmod g+w /sys/class/backlight/*/brightness

  # Leds
  chgrp video /sys/class/leds/*/brightness
  chmod g+w /sys/class/leds/*/brightness
}

usage () {
cat<<EOF
Usage: set-light [OPTION] [VALUE]

Description:
  Sets backlight brightness value. Add '-r' to use percentage
  (relative) values rather than absolute. '-a' means absolute
  and is the default value.

  set-light only supports a single option before VALUE. Do not
  separate command line arguments into multiple options.

  Returns current brightness if called with no value argument.

Options:
  -m               set minimum value
  -M               set maximum value
  -d[r|a] VALUE    decrease by VALUE
  -u[r|a] VALUE    increase by VALUE
  -[s][r|a] VALUE  set VALUE (default option)
  -v | --version   print version
  -h | --help      show this help message

It also supports some options for backward compatibility with other
programs (such as '-rS' for light) so that it can act as a partial
drop-in replacement, though they are not openly encouraged as they
may be removed in future versions and therefore support is not
granted.

Examples:
  set-light -r
   get current backlight percentage
  set-light -M
   set maximum brightness
  set-light -d 15
   decrease brightness by 15
  set-light -ur 5
   increase brightness by 5%
  set-light -r 50
   set brightness to half"""
EOF
}

version () {
  echo "set-light | version 0.0.2"
}

parse_perc () {
  if [ -n "$1" ]; then
    res="$(( $1 *  max_brightness / 100 ))"
  else # with no additional argument
    echo "$(( cur_brightness * 100 / max_brightness ))"
    exit
  fi
}

parse_perc "$step"
abs_step="$res"

case "$1" in
  "") echo "$cur_brightness"; exit ;;
  -m) b="0" ;;
  -M) b="$max_brightness" ;;
  -dr|-rd|-U) b=$(( cur_brightness - abs_step )) ;;
  -ur|-ru|-A) b=$(( cur_brightness + abs_step )) ;;
  -d|-da|-ad) b=$(( cur_brightness - step )) ;;
  -u|-ua|-au) b=$(( cur_brightness + step )) ;;
  -r|-sr|-rs|-S|-p) parse_perc "$2"; b="$res" ;;
  -a|-s|-sa|-as|-rS) b="$2" ;;
  -R|--rules) set_rules; exit ;;
  -v|--version) version; exit ;;
  -h|--help) usage; exit ;;
  -*) echo "error: invalid argument: ${1}"; exit 1 ;;
  *) b="$1" ;;
esac

[ "$b" -lt "$min" ] && b=0
[ "$b" -gt "$max" ] && b="$max_brightness"

backlight_dev="$backlight_dir/$(ls "${backlight_dir}" | head -n 1)"
echo "${b}" > "$backlight_dev/$brightness_file"
